# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20171110_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reloj',
            name='imagen',
            field=models.ImageField(default='/catalog/static/images/productos/default.jpg', help_text='Introducir imagen del producto[opcional]', upload_to='catalog/static/images/productos'),
        ),
    ]
